name: Sync GitLab Upstream

on:
  schedule:
    - cron: '17 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync from GitLab to GitHub
        uses: aormsby/Upstream-Sync@v3.4.1
        with:
          target_sync_branch: 'master'
          upstream_sync_repo: 'https://gitlab.com/rainlash/lt-maker.git'
          upstream_sync_branch: 'master'
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
