name: Sync GitLab Upstream

on:
  schedule:
    - cron: '17 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3
        with:
          ref: master
          persist-credentials: false

      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          target_branch: 'master'
          upstream_repository: 'rainlash/lt-maker'
          upstream_branch: 'master'
          domain: 'gitlab.com'
          github_token: ${{ secrets.GITHUB_TOKEN }}
