name: Sync GitLab Upstream

on:
  schedule:
    - cron: '17 * * * *'   # Runs at HH:17 every hour
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Sync upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          target_sync_branch: 'master'
          upstream_sync_repo: 'https://gitlab.com/rainlash/lt-maker.git'
          upstream_sync_branch: 'master'
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
